version: '3.7'

services:
  otp-auth:
    image: ferretgo:latest
    build:
      context: .
    command: uvicorn otp_auth.main:app --reload --host 0.0.0.0 --port 5000 --log-level=debug
    environment:
      PYTHONPATH: /src
    ports:
      - 5000:5000
    volumes:
      - ./:/src
